typography_spectrum: 0.7716287604998797
color:
  brandColors:
    - '#17BEBB'
    - '#2E282A'
    - '#CD5334'
    - '#EDB88B'
    - '#FAD8D6'
  brandStrength: 0.03168870694935322
  lightness: 0.053476352244615555
  saturation: 0.007616834482178092
  rhythmicContrast: 0.14802339999005198
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 0.675306670833379
analytics:
  google: UA-46064295-2
  facebook: null
  twitter: null
name: lol internet
cta:
  domain: null
  bucket: null
  version: null
favicon: null
purpose: []
